# Generated by Django 4.2.1 on 2023-05-28 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fanatico',
            old_name='pais_origen_id',
            new_name='abono_origen_id',
        ),
    ]
